### ISSUE TITLE
Connect Glossary to the clauses list in Tagging base

### ISSUE THREAD

**Issue by morchickit** [TCLP-UoC/Glossary#61]
Investigate how to automatically update between two bases

**Comment by Simone-TCLP** [comment]
Hi @morchickit 

Here is a share link to TCLP's Airtable database that contains most data on our climate clauses. The base is called Tagging Base - Simone access only. 

https://airtable.com/shr5ITqr8fOECQthj

I'd like this to be our master database of climate clauses - a master in the sense that it holds content needed for our data strategy to the fullest extent possible. 

My question is if we can link Glossary base to Tagging Base so that the Glossary base/ Used in field pulls data from the Tagging Base:

how and where do we put the links to the climate clause web pages in the Tagging Base? Do we create a new column containing the webpage or can you configure the field settings for Child's Name so we can insert a hyperlink into that one?

Let me know if you'd like to discuss,

**Comment by Simone-TCLP** [comment]
I think my preference is to hyperlink to the website from the child's name field. Is that possible?

**Comment by morchickit** [comment]
@Simone-TCLP @Humzah-TCLP - I have connected between the tagging base and the Glossary base. You can see it here -https://airtable.com/app78p8j3otk9SME6/tbl6wuT1Fw8u90K34/viwQn23ucYhTbzNvy?blocks=hide

I have then added to the tagging base a column name URL that link each clause to its webpage.  I used a formula for it, but some clauses has the word 'new' in the URL so I had to check it manually. You can see I didn't find some classes' URL so please help me feel it in. 

Let me know if this is how you wanted to implement it. If it's a go then Adam can work on other task that based on connecting clauses.

**Comment by Humzah-TCLP** [comment]
> 

@morchickit Thank you! 

This looks great. You won't have found a URL for some of the clauses because they are not currently published on the website. These are:

- Camden
- Conny
- Jamie
- Josie
- Phillipe 

The clauses that are missing a URL but are on our website are: 

- Paolo’s clause: [https://chancerylaneproject.org/climate-clauses/repair-or-refurbishment-in-insurance-claims/](https://chancerylaneproject.org/climate-clauses/repair-or-refurbishment-in-insurance-claims/) 
- William’s clause: [https://chancerylaneproject.org/climate-clauses/heads-of-terms-for-landowner-collaboration-on-environmental-schemes/](https://chancerylaneproject.org/climate-clauses/heads-of-terms-for-landowner-collaboration-on-environmental-schemes/)

It says I can't edit the field. Let me know if you have any questions.

**Comment by Humzah-TCLP** [comment]
In terms of how its implemented relates to issue #45 - a 'Used in' section with a list of hyperlinked clauses that the term is used in. Shall we have a call to discuss? Have some additional questions on the tagging base also, mainly how to best export the data.

**Comment by morchickit** [comment]
Great, I added the missing clauses URL. 

I thought that on #45 we agreed to connect up to 5 clauses in the format of Child's Name - Clause's title  and hyperlink, is this not correct? 

Happy to discuss Tagging base, but we might need to wait for @Simone-TCLP as she is the main maintainer.

**Comment by Humzah-TCLP** [comment]
Thank you! 

On #45 we connect all of the relevant clauses but show the first 5 (in alphabetical order) with a 'see more' function for terms with >5 clauses. 

That's OK - we can wait until she's back. I spoke with her earlier and it was mostly about the best way to export data from the tagging base.

**Comment by morchickit** [comment]
Happy to go on a quick call tomorrow then if needed too

**Comment by Humzah-TCLP** [comment]
What time suits?

**Comment by morchickit** [comment]
I am closing this now, as this is done
