### ISSUE TITLE
Like for Like - margins for this page are wider than other pages

### ISSUE THREAD

**Issue by Simone-TCLP** [TCLP-UoC/Glossary#73]
@akariv 

See screenshot here: 
<img width="825" alt="Screenshot 2022-10-20 at 19 48 41" src="https://user-images.githubusercontent.com/104088714/197032755-e11d0211-bb5d-462f-b304-2263d8e15c93.png">

**Comment by akariv** [comment]
This is caused because some of the reference titles contain links instead
of just English text.
In this case, this is the culprit:
https://airtable.com/app78p8j3otk9SME6/tblBEMsjWlL3nG7s0/viwrY8c765G9MHV3q/rec7LBrb8CqMQNjaW?blocks=hide

Please make sure the titles are only the english text to fix this issue.
